# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: True

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_system_dependencies:
      - python -m pip install wheel==0.38.4 setuptools==57.1.0
    post_create_environment:
      - python -m pip install wheel==0.38.4 setuptools==57.1.0
    post_install:
      - python -m pip install wheel==0.38.4 setuptools==57.1.0
    post_build:
      - python -m pip install wheel==0.38.4 setuptools==57.1.0

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - camera_obs
        - doc
        - train
        - ray