---
benchmark:
  name: "Driving SMARTS 2023.3"
  message: |
    This is the Driving SMARTS 2023.3 benchmark.

    For context see: 
        - https://smarts-project.github.io/competition/2023_driving_smarts/
        - https://codalab.lisn.upsaclay.fr/competitions/
  eval_episodes: 50
  debug:
    serial: True
  shared_env_kwargs:
    seed: 42
    headless: False
  envs:
    platoon:
      loc: "smarts.env:platoon-v0"
      scenarios:
        - /home/kyber/driving-smarts-2.competition-scenarios/t3/training/ffd10ec2-715b-48af-a89d-b11f79927f63_agents_1
      kwargs:
        seed: 42
      metric_formula: smarts/benchmark/driving_smarts/v2023/metric_formula_platoon.py
