# smarts/benchmark/driving_smarts_v2023/config.yaml
---
benchmark:
  name: "Driving SMARTS V2023"
  message: | # A useful message given at the start of the benchmark.
    This is the Driving SMARTS 2023 benchmark.
    For context see: 
        - https://codalab.lisn.upsaclay.fr/competitions/
        - https://smarts-project.github.io/archive/
  eval_episodes: 3
  debug:
    serial: True
  shared_env_kwargs:
    seed: 42
    headless: True
  shared_metric_params:
    dist_completed: {w: 0.35, wrt: self}
    time: {w: 0.25}
    dist_to_obstacles: {w: 0.15, ignore: [ego, Leader-007]}
    gap: {w: 0}
    jerk_linear: {w: 0.15}
    lane_center_offset: {w: 0.1}
    speed_limit: {w: 0}
    wrong_way: {w: 0}
  envs:
    # standard:
    #   loc: "smarts.env:driving-smarts-v2023"
    #   scenarios:
    #     - scenarios/sumo/straight/3lane_cruise_agents_1
    #   kwargs:
    #     seed: 42
    # turns:
    #   loc: "smarts.env:driving-smarts-v2023"
    #   scenarios:
    #     - scenarios/sumo/intersections/1_to_2lane_left_turn_c_agents_1
    #   kwargs:
    #     seed: 42
    platoon:
      loc: "smarts.env:platoon"
      scenarios:
        # - scenarios/sumo/platoon/straight_agents_1
        # - scenarios/sumo/platoon/fork_agents_1
        # - scenarios/sumo/platoon/merge_exit_agents_1
        # - scenarios/sumo/platoon/fork_sumo_t_agents_1
        - scenarios/sumo/platoon/straight_sumo_t_agents_1
        # - scenarios/argoverse/platoon/map_3_agents_1
        # - scenarios/argoverse/platoon/map_4_agents_1
        # - scenarios/argoverse/platoon/map_5_agents_1
      kwargs:
        seed: 42
      metric_params:
        dist_completed: {w: 0.35, wrt: Leader-007}
        time: {w: 0}
        gap: {w: 0.25}
