smarts:
  # Environment
  head: False # If True, enables Envision display.
  sumo_gui: False # If True, enables sumo-gui display.
  num_stack: 3 # Number of frames to stack as input to policy network.
  agent_locator: inference:contrib-agent-v0
  env_id: smarts.env:platoon-v0  
  scenarios: 
    - "3lane_merge_single_agent"

  # Training
  epochs: 5 # 5_000 # Number of training loops.

  # Training per scenario
  train_steps: 5_000
  checkpoint_freq: 2_500 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 10 # Number of evaluation epsiodes.
  eval_freq: 2_500 # Evaluate the trained model every eval_freq steps and save the best model.
